### PR TITLE
Enhancements: event subscription

### PR DESCRIPTION
**Pull request by AsLogd**
Added a prompt function. Added localstorage functions to handle persistence.
On the first visit the user is asked if he wants to subscribe to all events.
The user can subscribe/unsubscribe by clicking an event.
User gets a desktop notification 5 minutes prior to subscribed event start.
Fixed:
notification logo path
notification autoclose

### CODE REVIEW

**Comment by casassg** [comment]
added:

- Text telling user how to subscribe to events
- Replace unicode emoji with FontAwesome one. In my computer it was not showing properly as it doesnt have emoji compatibility

**Review by AsLogd — COMMENTED** [review]
wow 7k footprint. I thought it was bigger. We may aswell change the menu symbol. And I don't know if there is any other symbol somewhere

**Comment by casassg** [comment]
The rest of symbols are shown fine. So I would keep them. Trust me, if they are shown in my computer then they are surely fine.

**Review by casassg — COMMENTED** [review]
Tried in Firefox and Chrome. I'm goint to try in Edge (edge case) and then approve the PR

**Comment by casassg** [comment]
Edge is not compatible. Moving on

**Review by casassg — APPROVED** [review]
tested on Firefox + Chrome (Win and Linux) . Edge is not compatible in general, but version compatible is showing correctly

**Pull request merged**
