### PR TITLE
Refactor npm scripts & add new Live

### PR DESCRIPTION
**Pull request by AsLogd**
Replaced gulp with npm scripts. Added new live

### CODE REVIEW

**Comment by casassg** [comment]
Added serve on watch (I usually want watch only when serving)

**Comment by casassg** [comment]
Fixed 2 bugs:

- Hours to seconds was not converting correctly. Dates in string are in format 12 AM/PM, so hours >12 were not converted correctly.  Replaced to `hour * 3600 + minute *60`
- Schedule.json was being cached between requests in the browser. To avoid that I added a get parameter in the path with the current time in epoch.

Quick request: 

- Could we remove the notify node? It's filling my notification tray when I'm on watch. Or keep it, it's not a big deal. @dasilvacontin  thoughts on this?

**Review by casassg — APPROVED** [review]

**Comment by dasilvacontin** [comment]
\o/

**Comment by dasilvacontin** [comment]
@casassg I personally ignore my notification tray. It doesn't bother me, but I guess a 'completion ping' would be nicer, and notif only if error, with message.

**Comment by casassg** [comment]
@dasilvacontin I removed the notif for dist finally (it was breaking the built on the server). Kept the watch notif.

**Pull request merged**
