### PR TITLE
add everis and verse to sponsors

### PR DESCRIPTION
**Pull request by casassg**
Basically this. Last sponsors to be added. Welcome to Everis and Verse!

### CODE REVIEW

**Comment by rgascons** [comment]
Could you please split the PR into "add everis and verse to sponsors" and "fix bloomberg logo" (or something among these lines)?

Otherwise LGTM

**Comment by casassg** [comment]
Here you go!

**Comment by Dirbaio** [comment]
:heart:

**Comment by rgascons** [comment]
:(

**Pull request merged**
