### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by casassg**
Add travis to run the linters

### CODE REVIEW

**Comment by casassg** [comment]
Please see this: https://travis-ci.org/hackupc/frontend/builds/262490397

**Comment by wailingtam** [comment]
I already said it in the PR I integrated the linter that there were a few hundreds of style errors 🙃

**Comment by casassg** [comment]
Yay. Is there any way to have it automatically fixed (or at least some?)

**Comment by wailingtam** [comment]
I think some of the js ones can be fixed automatically. Will try to do it. Regarding html and scss I believe not

**Comment by casassg** [comment]
I fixed all the js. Only css and html missing _sigh_

**Comment by casassg** [comment]
closing this as its stale now

**Pull request closed without merging**
