### PR TITLE
Legal documents updated

### PR DESCRIPTION
**Pull request by oriolclosa**
## What this PR does / Why we need it
Fixes a couple of typos and changes to legal documents.

## Some questions
- [X] I have read the contributing guidelines
- [X] I abide by this repository Code of Conduct

### CODE REVIEW

**Comment by oriolclosa** [comment]
Please wait for Faix to review legal documents.

**Review by faix — APPROVED** [review]
Legal docs look good to me.

**Review by AsLogd — APPROVED** [review]
Lgtm

**Comment by oriolclosa** [comment]
Perfecte, merging!

**Pull request merged**
