### PR TITLE
Add new sponsors and partner logos

### PR DESCRIPTION
**Pull request by wailingtam**
- [x] Add **Itequia** when img is available

### CODE REVIEW

**Comment by casassg** [comment]
Are all logos formatted? https://github.com/hackupc/frontend#add-new-logo-images-for-sponsors-and-partners

**Comment by wailingtam** [comment]
Yes, they are. Although I made the GFT img 600x200 px since it is so "short". And 400 left too much empty space around it, I forgot to comment about it.

**Comment by casassg** [comment]
Leave the empty space. This is basically so that with css they are all the same and therefore are shown the same way. In this case I believe it would be okay as GFT is wider and the css scales the width

**Comment by wailingtam** [comment]
and so the height proportionally to the width value 😆
I tried 400 before making the decision ofc.
But if we're gonna make changes to the styles I won't discuss it further.

This is how they look like:
**200**
screen shot 2017-09-04 at 01 55 57

**400**
screen shot 2017-09-04 at 01 53 14

**Review by casassg — APPROVED** [review]
Okay, it looks good to me. Ship it 👍

**Comment by casassg** [comment]
Not sure if merging this now or waiting for Itequia

**Comment by wailingtam** [comment]
I think we were going to wait ☺️

**Pull request merged**
