### PR TITLE
Add meta tags for sharing awesomeness

### PR DESCRIPTION
**Pull request by dasilvacontin**

### CODE REVIEW

**Comment by mllobet** [comment]
LGTM, merging.

**Comment by Dirbaio** [comment]
BARCELOHA

:(

**Comment by mllobet** [comment]
PESADO

**Comment by Dirbaio** [comment]
pesado yo? :cry:

**Comment by mvdan** [comment]
lol the email signature @mllobet

**Comment by mllobet** [comment]
Spooky, I'm deleting this. Does it even stay?

**Comment by mvdan** [comment]
Does what stay?

**Comment by mllobet** [comment]
PR comment histories

**Comment by mvdan** [comment]
Not AFAIK

**Comment by dasilvacontin** [comment]
@mllobet Everything stays in GH's database. <3

**Comment by mvdan** [comment]
dude this was literally a week ago, wth

**Comment by Dirbaio** [comment]
spaaaaaaaaaaaaaaaaaam

**Pull request merged**
