### PR TITLE
Optimize leaves animation.

### PR DESCRIPTION
**Pull request by Dirbaio**
The difference is most visible on mobile devices :)
- Use deltatime so the animation doesn't go slower if you don't reach 60FPS
- Do not create Image objects every frame.
- Change the page container to its own compositing layer so the page isn't repainted every frame.

### CODE REVIEW

**Comment by MarceColl** [comment]
Tested in local. For firefox there is a big improvement. CPU usage is still very high tho.

@casassg can you merge into master?
Tot i aixo noto mes stuttering a chrome amb aixo, algu altre ho pot provar en local?

**Review by ani300 — APPROVED** [review]
lgtm

**Comment by casassg** [comment]
:+1:

**Comment by dasilvacontin** [comment]
kudos

**Pull request merged**
