### PR TITLE
Fix wrong favicon

### PR DESCRIPTION
**Pull request by wailingtam**
We've been using the old background color favicon all this time 😕

### CODE REVIEW

**Comment by casassg** [comment]
Please could you explain the differences? I can see the difference. Is it with the tiles background? If so, I think the current one offers more contrast imo.

**Comment by wailingtam** [comment]
Yes, it's the "background" tile color.
I also get what you mean with the contrast, I thought so too. But I just wanted to put the correct one. Like the one used on slack, fb, etc. any HackUPC profile pic.

**Comment by casassg** [comment]
It may create inconsistency w backend as we use the current one there as well

**Comment by wailingtam** [comment]
Then we should change it in the backend too. Not gonna avoid this just because it's wrong in both places am I correct?

**Review by casassg — APPROVED** [review]
you got a point there

**Comment by wailingtam** [comment]
Thanks ❤️

**Pull request merged**
