### PR TITLE
Fix button padding

### PR DESCRIPTION
**Pull request by Towerthousand**

### CODE REVIEW

**Comment by mvdan** [comment]
CC @dasilvacontin

**Comment by Dirbaio** [comment]
NACK, la solucion buena es no poner un `<button>` dentro de un `<a>`

**Comment by mvdan** [comment]
patches welcome @Dirbaio :)

**Comment by dasilvacontin** [comment]
I'll review later today.

**Comment by mvdan** [comment]
@dasilvacontin I'll assume you're fine with me merging later today, unless you do review

**Comment by dasilvacontin** [comment]
@mvdan You assumed wrong.

I think there might be some kind of browser rendering difference, because with these changes it doesn't look vertically centered at all, at least on my machine:

screenshot 2016-01-19 23 23 16

Can you confirm @Towerthousand? Can you people share how it currently looks like to you?

**Comment by dasilvacontin** [comment]
If that's the case, I think it's related to the font.

**Comment by mvdan** [comment]
I know my assumption was wrong, I was being ironic.

**Comment by dasilvacontin** [comment]
@mvdan Thanks for merging then.

**Comment by dasilvacontin** [comment]
What browser are you using? These changes look good on Firefox (Mac), but don't look good on Chrome/Safari (Mac). I'll check on Windows.

It also means that all text positioning on Firefox looks slightly off, and not exactly where it was meant to be.

**Comment by dasilvacontin** [comment]
Looks wrong on Edge/Firefox/Chrome (Windows). Can anybody try it out on Linux? And/or confirm my findings.

**Comment by mvdan** [comment]
Both Chrome on Linux and Chrome on Android show master correctly.

**Comment by Towerthousand** [comment]
Can we just agree to not use <button> and be done with the problem?

<button> browser styling is 200% probably what's messing this up

**Comment by Towerthousand** [comment]
this is fixed in #5.

**Comment by dasilvacontin** [comment]
I just confirmed with @Towerthousand that this rendering difference is caused by the poor font.

**Pull request merged**
