### PR TITLE
Remove nasty <button> tags

### PR DESCRIPTION
**Pull request by Towerthousand**
Whenever I'm feeling `<button>` I stop being `<button>` and I start being `<a>`wesome

:beers: 
:balloon: 
:yellow_heart:

### CODE REVIEW

**Comment by Towerthousand** [comment]
@dasilvacontin this is actually the deployed branch atm, test it out at [the actual site](https://hackupc.com) :+1:

**Comment by dasilvacontin** [comment]
I was hoping that this would fix the problem, but it doesn't. :/

**Comment by dasilvacontin** [comment]
I'll try with some other person's computer today, because if this is not related to my machine then it's a quite ugly rendering bug/whatever.

**Comment by dasilvacontin** [comment]
I tried with several other computers and it still looks wrong. Any other browser/OS combination where it actually looks good? Otherwise we should revert the padding changes.

Regarding this PR's changes, LGTM, let's get rid of the `button`s.

**Comment by mvdan** [comment]
Looks good on both Chrome and Android (made sure not to be running the old cached version).

**Comment by dasilvacontin** [comment]
@mvdan OS? Can you share a screenshot too, to be sure?

**Comment by mvdan** [comment]
Linux.

**Comment by mvdan** [comment]
Well, you can argue that it's slightly lower than expected, but I didn't even notice without enlarging the buttons.

**Comment by dasilvacontin** [comment]
@mvdan I'm not complaining about that, I still experience the same I described in #4.

**Comment by mvdan** [comment]
Since this isn't worsening things and we can agree on removing the buttons, merging.

**Pull request merged**
