### PR TITLE
Add Prizes

### PR DESCRIPTION
**Pull request by mauriciabad**
**IMPORTANT**: This branch has to be merged and deployed once the opening ceremony finishes. Not before.

### CODE REVIEW

**Review by AlbertSuarez — COMMENTED** [review]
I would change the challenges section removing the HackUPC prizes and publishing the challenges from the sponsors. Then prepare another PR with just showing our prizes.
Also, please, change the font of the countdown. It has to be the same as the whole website (I mean, the one that was used before this PR).

**Comment by mauriciabad** [comment]
Now challenges are visible, but not prizes. (check 2019 branch)
I'm aware of the countdown. I'm working on it.

**Comment by AlbertSuarez** [comment]
Okay cool, perfect. Let me know when the countdown is updated and I'll approve the PR. Good job!

**Comment by mauriciabad** [comment]
The countdown is ready and already deployed :)

**Pull request merged**
